---
title: "03 - Reproducible Comprehension Check"
author: "Alessandro Corradini - Harvard Data Science Professional"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

### **Why R Markdown?**

Why might you want to create a report using R Markdown?

- R Markdown has better spell-checking tools than other word processors.
- R Markdown allows you to automatically add figures to the final document. [X]
- R Markdown final reports have smaller file sizes than Word documents.
- R Markdown documents look identical to the final report.


<br/>

### **Naming an R Chunk**

You have a vector of student ```heights``` called heights. You want to generate a histogram of these heights in a final report, but you don’t want the code to show up in the final report. You want to name the R chunk “histogram” so that you can easily find the chunk later.

Which of the following R chunks does everything you want it to do?

- ``` /{r, histogram, echo=FALSE} hist(heights)``` 
- ``` {r histogram} hist(heights) ```      
- ``` {r, echo=FALSE} hist(heights) ```      
- ``` {r histogram, echo=FALSE} hist(heights)``` [X]     

<br/>

### **R Markdown Report**

Below is a section of R Markdown code that generates a report.

<code>
&#8208;&#8208;&#8208; <br/>
  title: "Final Grade Distribution" <br/>
  output: pdf_document <br/>
  &#8208;&#8208;&#8208; <br/>
  &#96;&#96;&#96;{r, echo=FALSE} <br/>
  load(file="my_data.Rmd") <br/>
  summary(grades) <br/>
  &#96;&#96;&#96;
</code>


 Select the statement that describes the file report generated by the R markdown code above.

- A PDF document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will not be included in the final report. [X]
- A PDF document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will be included in the final report.
- An HTML document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will not be included in the final report.
- A PDF document called “Final Grade Distribution” that is empty because the argument echo=FALSE was used.

<br/>

#### **Report File Format**

The user specifies the output file format of the final report when using R Markdown.

Which of the following file types is NOT an option for the final output?

- .rmd [X]
- .pdf
- .doc
- .html